# Generated by Django 4.2.4 on 2023-09-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_in_stock',
            field=models.CharField(max_length=100),
        ),
    ]
